# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "github-action-test-workflow" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: 'my-test-image'
  PROJECT_ID: 'ons-ci-aims'
  AR_REPO_LOCATION: 'europe-west2'
  AR_URL: 'europe-west2-docker.pkg.dev/ons-ci-aims/temp-aims-github-actions'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/709138365636/locations/global/workloadIdentityPools/github-actions-test/providers/github-actions-provider-test'

permissions:
  contents: read
  id-token: write

jobs:
  authenticate-to-gcp:
    runs-on: ubuntu-latest
    outputs:
      access_token: ${{ steps.auth.outputs.access_token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Set up JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.0
        with:
          gradle-version: wrapper
      - run: ./gradlew build --exclude-task test
  test:
    runs-on: ubuntu-latest
    needs: [ authenticate-to-gcp, build ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Set up JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.0
        with:
          gradle-version: wrapper
      - env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ needs.authenticate-to-gcp.outputs.access_token }}
        run: ./gradlew test -PexcludeTests=**/PubSubComponentTest*

  build-image-push-to-artifact-registry:
    runs-on: ubuntu-latest
    needs: [ authenticate-to-gcp, test ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
      #    permissions:
      #      contents: read
      #      id-token: write
      #    runs-on: ubuntu-latest
      #    steps:
      #      - name: Checkout repository
      #        uses: actions/checkout@v5.0.0

      #      - name: Google Auth
      #        id: auth
      #        uses: 'google-github-actions/auth@v3'
      #        with:
      #          project_id: ${{ env.PROJECT_ID }}
      #          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Read value from file
        id: read_file
        run: |
          VALUE=$(cat version.txt)
          echo "VALUE=$VALUE" >> $GITHUB_ENV

      - name: Use the value
        run: echo "The value is ${{ env.VALUE }}"

      #      - name: Set up JDK 21
      #        uses: actions/setup-java@v5.0.0
      #        with:
      #          java-version: '21'
      #          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      #      - name: Setup Gradle 8.11
      #        uses: gradle/actions/setup-gradle@v5.0.0
      #        with:
      #          gradle-version: wrapper
      #      - run: ./gradlew build --exclude-task test
      #      - run: echo "The release-candidate version was ${{ steps.setup-gradle.outputs.gradle-version }}"
      ##      - run: ./gradlew test -PexcludeTests=**/PubSubComponentTest*

      #      - name: Docker Auth
      #        id: docker-auth
      #        uses: 'docker/login-action@v3'
      #        with:
      #          username: 'oauth2accesstoken'
      #          password: '${{ steps.auth.outputs.access_token }}'
      #          registry: '${{ env.AR_REPO_LOCATION }}-docker.pkg.dev'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ env.AR_REPO_LOCATION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ env.VALUE }}" .
          docker build -t "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:latest" .

      - name: Push Docker image
        run: |
          docker push "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}" --all-tags


    # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
    # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
    #
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    #   with:
    #     gradle-version: '8.9'
    #
    # - name: Build with Gradle 8.9
    #   run: gradle build

#  dependency-submission:
#
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#
#    steps:
#      - uses: actions/checkout@v5.0.0
#      - name: Set up JDK 21
#        uses: actions/setup-java@v5.0.0
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#
#      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
#      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
#      - name: Generate and submit dependency graph
#        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0