name: Java CI with Gradle and Docker

on:
  push:
    branches: [ "github-action-test-workflow" ]
  pull_request:
    branches: [ "github-action-test-workflow" ]

env:
  IMAGE_NAME: 'my-test-image'
  PROJECT_ID: 'ons-ci-aims'
  AR_REPO_LOCATION: 'europe-west2'
  AR_URL: 'europe-west2-docker.pkg.dev/ons-ci-aims/temp-aims-github-actions'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/709138365636/locations/global/workloadIdentityPools/github-actions-test/providers/github-actions-provider-test'

permissions:
  contents: read
  id-token: write

jobs:
  build-test-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Set up JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and Test with Gradle
        uses: gradle/actions/setup-gradle@v5.0.0
        with:
          gradle-version: wrapper
      - run: ./gradlew build -PexcludeTests=**/PubSubComponentTest*

      - name: Read version from file
        id: read_file
        run: |
          VALUE=$(cat version.txt)
          echo "VALUE=$VALUE" >> $GITHUB_ENV

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ env.AR_REPO_LOCATION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ env.VALUE }}" .
          docker build -t "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:latest" .

      - name: Push Docker image
        run: |
          docker push "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}" --all-tags

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5.0.0
      - name: Set up JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v5.0.0